coverage:
    status:
        project:
            default:
                target: 80% # TODO: switch back to auto
                threshold: 1% # the leniency in hitting the target
        patch:
            default:
                target: 85% # TODO: switch back to 100%
