coverage:
    status:
        project:
            default:
                target: 68% # TODO: switch back to auto
                threshold: 1% # the leniency in hitting the target
        patch:
            default:
                target: 75% # TODO: switch back to 100%
