name: Pytest
description: Run tests with coverage and typeguard
inputs:
    CODECOV_TOKEN:
        type: string
        required: true

runs:
    using: "composite"
    steps:
        - name: Run tests with coverage
          run: |
              source .venv/bin/activate
              pytest -n auto -m "not slow" --cov --cov-report=xml:coverage.xml --cov-report=term-missing --typeguard-packages=pytorch-ie
          shell: bash

        - name: Upload coverage report to Codecov
          uses: codecov/codecov-action@v4
          with:
              files: ./coverage.xml
              fail_ci_if_error: true
          env:
              CODECOV_TOKEN: ${{ inputs.CODECOV_TOKEN }}
