name: Safety
description: Run safety check on dependencies

runs:
    using: "composite"
    steps:
        - name: Upload documentation
          if: matrix.session == 'safety'
          run: |
              source .venv/bin/activate
              poetry export -f "requirements.txt" -o "requirements.txt"
              safety check --full-report --file=requirements.txt
          shell: bash
