name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main, "release/*"]

env:
    FORCE_COLOR: "1"

jobs:
    pre-commit:
        name: Pre-commit
        runs-on: "ubuntu-latest"
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4
            - uses: ./.github/actions/init-env
              with:
                  os: "ubuntu-latest"
                  python: "3.9"
            - name: Run pre-commits
              uses: ./.github/actions/pre-commit

    pytest:
        name: Pytest ${{ matrix.python }} / ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - { python: "3.9", os: "ubuntu-latest" }
                    # - { python: "3.9", os: "macos-latest" }
                    # - { python: "3.9", os: "windows-latest" }
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4
            - name: Set up python environment
              uses: ./.github/actions/init-env
              with:
                  os: ${{ matrix.os }}
                  python: ${{ matrix.python }}
            - name: Run tests with coverage
              uses: ./.github/actions/pytest

    coverage:
        name: Check coverage
        runs-on: "ubuntu-latest"
        needs: pytest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4
            - name: Set up python environment
              uses: ./.github/actions/init-env
              with:
                  os: "ubuntu-latest"
                  python: "3.9"
            - name: Create, show and upload coverage report
              uses: ./.github/actions/coverage
              with:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    # safety:
    #     name: Safety
    #     runs-on: "ubuntu-latest"
    #     steps:
    #         - name: Check out the repository
    #           uses: actions/checkout@v4
    #         - name: Set up python environment
    #           uses: ./.github/actions/init-env
    #           with:
    #               os: "ubuntu-latest"
    #               python: "3.9"
    #         - name: Run safety check on dependencies
    #           uses: ./.github/actions/safety

    # typeguard:
    #     name: Typeguard
    #     runs-on: "ubuntu-latest"
    #     steps:
    #         - name: Check out the repository
    #           uses: actions/checkout@v4
    #         - name: Set up python environment
    #           uses: ./.github/actions/init-env
    #           with:
    #               os: "ubuntu-latest"
    #               python: "3.9"
    #         - name: Run typeguard tests
    #           uses: ./.github/actions/typeguard
