name: Test

on:
  pull_request: {}
  push:
    branches: main
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies with poetry
        run: |
          pip install poetry
          poetry install

      - run: poetry run isort --diff .
      - run: poetry run black --check .
      - run: poetry run mypy
      - run: poetry run pytest --cov --cov-fail-under=100
